@InventoryManagement.Api_HostAddress = http://localhost:5161

GET {{InventoryManagement.Api_HostAddress}}/api/products
Accept: application/json

###

POST {{InventoryManagement.Api_HostAddress}}/api/products
Content-Type: application/json
Accept: application/json

{
  "name": "Keyboard",
  "description": "Mechanical keyboard",
  "price": 79.99,
  "quantity": 15
}

###