@InventoryManagement.Api_HostAddress = http://localhost:5161

### Get all products

GET {{InventoryManagement.Api_HostAddress}}/api/products
Accept: application/json


### Get product by ID

GET {{InventoryManagement.Api_HostAddress}}/api/products/2
Accept: application/json


### Create product

POST {{InventoryManagement.Api_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "Keyboard",
  "description": "Mechanical keyboard",
  "price": 79.99,
  "quantity": 15
}


### Update product

PUT {{InventoryManagement.Api_HostAddress}}/api/products/2
Content-Type: application/json

{
  "id": 2,
  "name": "Gaming Keyboard",
  "description": "RGB mechanical keyboard",
  "price": 99.99,
  "quantity": 10
}


### Add inventory

PATCH {{InventoryManagement.Api_HostAddress}}/api/products/2/stock
Content-Type: application/json

{
  "change": 10
}


### Remove inventory

PATCH {{InventoryManagement.Api_HostAddress}}/api/products/2/stock
Content-Type: application/json

{
  "change": -3
}


### Test insufficient inventory

PATCH {{InventoryManagement.Api_HostAddress}}/api/products/2/stock
Content-Type: application/json

{
  "change": -1000
}


### Test product validation

POST {{InventoryManagement.Api_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "",
  "description": "Invalid product",
  "price": -50,
  "quantity": -10
}


### Delete product

DELETE {{InventoryManagement.Api_HostAddress}}/api/products/2