@InventoryManagement.Api_HostAddress = http://localhost:5161

GET {{InventoryManagement.Api_HostAddress}}/api/products
Accept: application/json

###

POST {{InventoryManagement.Api_HostAddress}}/api/products
Content-Type: application/json
Accept: application/json

{
  "name": "Keyboard",
  "description": "Mechanical keyboard",
  "price": 79.99,
  "quantity": 15
}

###

PUT {{InventoryManagement.Api_HostAddress}}/api/products/2
Content-Type: application/json

{
  "id": 2,
  "name": "Gaming Keyboard",
  "description": "RGB mechanical keyboard",
  "price": 99.99,
  "quantity": 10
}

###

DELETE {{InventoryManagement.Api_HostAddress}}/api/products/2

###

GET {{InventoryManagement.Api_HostAddress}}/api/products/2
Accept: application/json